// Code generated by mockery v2.53.7. DO NOT EDIT.

package repository

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockRefreshTokenRepo is an autogenerated mock type for the RefreshTokenRepo type
type MockRefreshTokenRepo struct {
	mock.Mock
}

type MockRefreshTokenRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRefreshTokenRepo) EXPECT() *MockRefreshTokenRepo_Expecter {
	return &MockRefreshTokenRepo_Expecter{mock: &_m.Mock}
}

// FindByHash provides a mock function with given fields: ctx, tokenHash
func (_m *MockRefreshTokenRepo) FindByHash(ctx context.Context, tokenHash string) (int, time.Time, bool, error) {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for FindByHash")
	}

	var r0 int
	var r1 time.Time
	var r2 bool
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, time.Time, bool, error)); ok {
		return rf(ctx, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) time.Time); ok {
		r1 = rf(ctx, tokenHash)
	} else {
		r1 = ret.Get(1).(time.Time)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) bool); ok {
		r2 = rf(ctx, tokenHash)
	} else {
		r2 = ret.Get(2).(bool)
	}

	if rf, ok := ret.Get(3).(func(context.Context, string) error); ok {
		r3 = rf(ctx, tokenHash)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockRefreshTokenRepo_FindByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByHash'
type MockRefreshTokenRepo_FindByHash_Call struct {
	*mock.Call
}

// FindByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockRefreshTokenRepo_Expecter) FindByHash(ctx interface{}, tokenHash interface{}) *MockRefreshTokenRepo_FindByHash_Call {
	return &MockRefreshTokenRepo_FindByHash_Call{Call: _e.mock.On("FindByHash", ctx, tokenHash)}
}

func (_c *MockRefreshTokenRepo_FindByHash_Call) Run(run func(ctx context.Context, tokenHash string)) *MockRefreshTokenRepo_FindByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRefreshTokenRepo_FindByHash_Call) Return(userID int, expiresAt time.Time, revoked bool, err error) *MockRefreshTokenRepo_FindByHash_Call {
	_c.Call.Return(userID, expiresAt, revoked, err)
	return _c
}

func (_c *MockRefreshTokenRepo_FindByHash_Call) RunAndReturn(run func(context.Context, string) (int, time.Time, bool, error)) *MockRefreshTokenRepo_FindByHash_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function with given fields: ctx, tokenHash
func (_m *MockRefreshTokenRepo) Revoke(ctx context.Context, tokenHash string) error {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenRepo_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type MockRefreshTokenRepo_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockRefreshTokenRepo_Expecter) Revoke(ctx interface{}, tokenHash interface{}) *MockRefreshTokenRepo_Revoke_Call {
	return &MockRefreshTokenRepo_Revoke_Call{Call: _e.mock.On("Revoke", ctx, tokenHash)}
}

func (_c *MockRefreshTokenRepo_Revoke_Call) Run(run func(ctx context.Context, tokenHash string)) *MockRefreshTokenRepo_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRefreshTokenRepo_Revoke_Call) Return(_a0 error) *MockRefreshTokenRepo_Revoke_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenRepo_Revoke_Call) RunAndReturn(run func(context.Context, string) error) *MockRefreshTokenRepo_Revoke_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllForUser provides a mock function with given fields: ctx, userID
func (_m *MockRefreshTokenRepo) RevokeAllForUser(ctx context.Context, userID int) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllForUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenRepo_RevokeAllForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllForUser'
type MockRefreshTokenRepo_RevokeAllForUser_Call struct {
	*mock.Call
}

// RevokeAllForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockRefreshTokenRepo_Expecter) RevokeAllForUser(ctx interface{}, userID interface{}) *MockRefreshTokenRepo_RevokeAllForUser_Call {
	return &MockRefreshTokenRepo_RevokeAllForUser_Call{Call: _e.mock.On("RevokeAllForUser", ctx, userID)}
}

func (_c *MockRefreshTokenRepo_RevokeAllForUser_Call) Run(run func(ctx context.Context, userID int)) *MockRefreshTokenRepo_RevokeAllForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockRefreshTokenRepo_RevokeAllForUser_Call) Return(_a0 error) *MockRefreshTokenRepo_RevokeAllForUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenRepo_RevokeAllForUser_Call) RunAndReturn(run func(context.Context, int) error) *MockRefreshTokenRepo_RevokeAllForUser_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, userID, tokenHash, expiresAt
func (_m *MockRefreshTokenRepo) Save(ctx context.Context, userID int, tokenHash string, expiresAt time.Time) error {
	ret := _m.Called(ctx, userID, tokenHash, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string, time.Time) error); ok {
		r0 = rf(ctx, userID, tokenHash, expiresAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenRepo_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockRefreshTokenRepo_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - tokenHash string
//   - expiresAt time.Time
func (_e *MockRefreshTokenRepo_Expecter) Save(ctx interface{}, userID interface{}, tokenHash interface{}, expiresAt interface{}) *MockRefreshTokenRepo_Save_Call {
	return &MockRefreshTokenRepo_Save_Call{Call: _e.mock.On("Save", ctx, userID, tokenHash, expiresAt)}
}

func (_c *MockRefreshTokenRepo_Save_Call) Run(run func(ctx context.Context, userID int, tokenHash string, expiresAt time.Time)) *MockRefreshTokenRepo_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string), args[3].(time.Time))
	})
	return _c
}

func (_c *MockRefreshTokenRepo_Save_Call) Return(_a0 error) *MockRefreshTokenRepo_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenRepo_Save_Call) RunAndReturn(run func(context.Context, int, string, time.Time) error) *MockRefreshTokenRepo_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRefreshTokenRepo creates a new instance of MockRefreshTokenRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRefreshTokenRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRefreshTokenRepo {
	mock := &MockRefreshTokenRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
