// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	repository "github.com/SephirothGit/warehouse/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// UserRepo is an autogenerated mock type for the UserRepo type
type UserRepo struct {
	mock.Mock
}

type UserRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepo) EXPECT() *UserRepo_Expecter {
	return &UserRepo_Expecter{mock: &_m.Mock}
}

// AssignRole provides a mock function with given fields: ctx, userID, roleID
func (_m *UserRepo) AssignRole(ctx context.Context, userID int, roleID int) error {
	ret := _m.Called(ctx, userID, roleID)

	if len(ret) == 0 {
		panic("no return value specified for AssignRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, userID, roleID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserRepo_AssignRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignRole'
type UserRepo_AssignRole_Call struct {
	*mock.Call
}

// AssignRole is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - roleID int
func (_e *UserRepo_Expecter) AssignRole(ctx interface{}, userID interface{}, roleID interface{}) *UserRepo_AssignRole_Call {
	return &UserRepo_AssignRole_Call{Call: _e.mock.On("AssignRole", ctx, userID, roleID)}
}

func (_c *UserRepo_AssignRole_Call) Run(run func(ctx context.Context, userID int, roleID int)) *UserRepo_AssignRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *UserRepo_AssignRole_Call) Return(_a0 error) *UserRepo_AssignRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserRepo_AssignRole_Call) RunAndReturn(run func(context.Context, int, int) error) *UserRepo_AssignRole_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, email, passwordHash
func (_m *UserRepo) Create(ctx context.Context, email string, passwordHash string) (int, error) {
	ret := _m.Called(ctx, email, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (int, error)); ok {
		return rf(ctx, email, passwordHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) int); ok {
		r0 = rf(ctx, email, passwordHash)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, passwordHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UserRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - passwordHash string
func (_e *UserRepo_Expecter) Create(ctx interface{}, email interface{}, passwordHash interface{}) *UserRepo_Create_Call {
	return &UserRepo_Create_Call{Call: _e.mock.On("Create", ctx, email, passwordHash)}
}

func (_c *UserRepo_Create_Call) Run(run func(ctx context.Context, email string, passwordHash string)) *UserRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *UserRepo_Create_Call) Return(_a0 int, _a1 error) *UserRepo_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepo_Create_Call) RunAndReturn(run func(context.Context, string, string) (int, error)) *UserRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function with given fields: ctx, email
func (_m *UserRepo) GetByEmail(ctx context.Context, email string) (repository.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 repository.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (repository.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) repository.User); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(repository.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepo_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type UserRepo_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *UserRepo_Expecter) GetByEmail(ctx interface{}, email interface{}) *UserRepo_GetByEmail_Call {
	return &UserRepo_GetByEmail_Call{Call: _e.mock.On("GetByEmail", ctx, email)}
}

func (_c *UserRepo_GetByEmail_Call) Run(run func(ctx context.Context, email string)) *UserRepo_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserRepo_GetByEmail_Call) Return(_a0 repository.User, _a1 error) *UserRepo_GetByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepo_GetByEmail_Call) RunAndReturn(run func(context.Context, string) (repository.User, error)) *UserRepo_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoleIDByName provides a mock function with given fields: ctx, name
func (_m *UserRepo) GetRoleIDByName(ctx context.Context, name string) (int, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetRoleIDByName")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepo_GetRoleIDByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoleIDByName'
type UserRepo_GetRoleIDByName_Call struct {
	*mock.Call
}

// GetRoleIDByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *UserRepo_Expecter) GetRoleIDByName(ctx interface{}, name interface{}) *UserRepo_GetRoleIDByName_Call {
	return &UserRepo_GetRoleIDByName_Call{Call: _e.mock.On("GetRoleIDByName", ctx, name)}
}

func (_c *UserRepo_GetRoleIDByName_Call) Run(run func(ctx context.Context, name string)) *UserRepo_GetRoleIDByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserRepo_GetRoleIDByName_Call) Return(_a0 int, _a1 error) *UserRepo_GetRoleIDByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepo_GetRoleIDByName_Call) RunAndReturn(run func(context.Context, string) (int, error)) *UserRepo_GetRoleIDByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoles provides a mock function with given fields: ctx, userID
func (_m *UserRepo) GetRoles(ctx context.Context, userID int) ([]string, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetRoles")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]string, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []string); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepo_GetRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoles'
type UserRepo_GetRoles_Call struct {
	*mock.Call
}

// GetRoles is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *UserRepo_Expecter) GetRoles(ctx interface{}, userID interface{}) *UserRepo_GetRoles_Call {
	return &UserRepo_GetRoles_Call{Call: _e.mock.On("GetRoles", ctx, userID)}
}

func (_c *UserRepo_GetRoles_Call) Run(run func(ctx context.Context, userID int)) *UserRepo_GetRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *UserRepo_GetRoles_Call) Return(_a0 []string, _a1 error) *UserRepo_GetRoles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepo_GetRoles_Call) RunAndReturn(run func(context.Context, int) ([]string, error)) *UserRepo_GetRoles_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserRepo creates a new instance of UserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepo {
	mock := &UserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
